!pip install pydantic==2.11.3
!pip install langchain==0.3.23
!pip install langchain-google-genai==2.1.3
!pip install langgraph==0.3.31
!pip install langchain-community==0.3.21
!pip install google-search-results==2.4.2
!pip install langchain-qdrant==0.2.0
!pip install langchain-google-vertexai==2.0.20
!pip install pymupdf4llm==0.0.21